// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/4/2026, 3:54:10 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/andreapiscioneri/Repo/Cascina-paradiso-bozza/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/andreapiscioneri/Repo/Cascina-paradiso-bozza/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/andreapiscioneri/Repo/Cascina-paradiso-bozza/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/andreapiscioneri/Repo/Cascina-paradiso-bozza/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/andreapiscioneri/Repo/Cascina-paradiso-bozza/plugins/**/*.{js,ts,mjs}","/Users/andreapiscioneri/Repo/Cascina-paradiso-bozza/composables/**/*.{js,ts,mjs}","/Users/andreapiscioneri/Repo/Cascina-paradiso-bozza/utils/**/*.{js,ts,mjs}","/Users/andreapiscioneri/Repo/Cascina-paradiso-bozza/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/andreapiscioneri/Repo/Cascina-paradiso-bozza/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/andreapiscioneri/Repo/Cascina-paradiso-bozza/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/andreapiscioneri/Repo/Cascina-paradiso-bozza/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;